# Generated by Django 5.1.1 on 2024-10-05 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('creditos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_curso', models.CharField(choices=[('obligatorio', 'Obligatorio'), ('optativo', 'Optativo')], max_length=12)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('híbrido', 'Híbrido')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_facultad', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('codigo_estudiante', models.IntegerField()),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=255)),
                ('correo_institucional', models.EmailField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.IntegerField()),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('estado_academico', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('graduado', 'Graduado'), ('expulsado', 'Expulsado')], max_length=255)),
                ('ciclo_actual', models.IntegerField()),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='server.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='id_facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.facultad'),
        ),
        migrations.CreateModel(
            name='HistorialAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('semestre', models.IntegerField()),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.curso')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=9)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('tipo', models.CharField(choices=[('user', 'Usuario'), ('bot', 'Bot')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='server.conversacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('matricula', 'Matrícula'), ('pension', 'Pensión'), ('otros', 'Otros')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], max_length=50)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.IntegerField()),
                ('semestre', models.IntegerField(default=1)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.curso')),
                ('id_plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.planestudio')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('estado', models.CharField(max_length=255)),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.estudiante')),
                ('id_plan_estudio_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.planestudiocurso')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitosPrevios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='server.curso')),
                ('id_curso_requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_requisito', to='server.curso')),
            ],
        ),
    ]
