# Generated by Django 5.1.1 on 2024-09-28 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('creditos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('semestre', models.IntegerField()),
                ('requisitos', models.IntegerField()),
                ('tipo_curso', models.CharField(choices=[('obligatorio', 'Obligatorio'), ('optativo', 'Optativo')], max_length=12)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('híbrido', 'Híbrido')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_facultad', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estudiante', models.IntegerField()),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=255)),
                ('correo_institucional', models.EmailField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.IntegerField()),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('estado_academico', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('graduado', 'Graduado'), ('expulsado', 'Expulsado')], max_length=255)),
                ('ciclo_actual', models.IntegerField()),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.carrera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='id_facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.facultad'),
        ),
        migrations.CreateModel(
            name='HistorialAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('semestre', models.IntegerField()),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.curso')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='MallaCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.curso')),
            ],
        ),
        migrations.CreateModel(
            name='MallasCurricularesCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.curso')),
                ('id_malla_curricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.mallacurricular')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=255)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.curso')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitosPrevios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='server.curso')),
                ('id_curso_requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_requisito', to='server.curso')),
            ],
        ),
    ]
