# Generated by Django 5.1.1 on 2024-09-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='user',
            field=models.CharField(max_length=15),
        ),
    ]
