# Generated by Django 5.1.1 on 2024-09-28 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_estudiante_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.estudiante')),
            ],
        ),
    ]
