# Generated by Django 5.1.1 on 2024-10-03 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_estudiantetoken'),
    ]

    operations = [
      

      
    
        migrations.AddField(
            model_name='matricula',
            name='ciclo',
            field=models.IntegerField(default=-1986),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='semestre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=9)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('matricula', 'Matrícula'), ('pension', 'Pensión'), ('otros', 'Otros')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], max_length=50)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.IntegerField()),
                ('semestre', models.IntegerField(default=1)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.curso')),
                ('id_plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.planestudio')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='id_plan_estudio_curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.planestudiocurso'),
            preserve_default=False,
        ),
     
    ]
